### ISSUE TITLE
Problems installing IPO

### ISSUE THREAD

**Issue by jheaton1** [glibiseller/IPO#10]
Hi,

I have some issues installing IPO. Among which include not loading 'curl' 'CAMERA' 'xcms' even though they are already installed and loaded using library. In addition I have the problem below:

Downloading github repo glibiseller/IPO@master
Installing IPO
Skipping 2 packages not available: CAMERA, xcms
"C:/PROGRA~1/R/R-32~1.1/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore CMD INSTALL  \
  "C:/Users/[...]/AppData/Local/Temp/Rtmpc1yP3q/devtoolsfa041361295/glibiseller-IPO-3738d2a"  \
  --library="[...]/R/win-library/3.2" --install-tests 

* installing *source* package 'IPO' ...
** R
** inst
** tests
** preparing package for lazy loading
Warning: replacing previous import by 'igraph::groups' when loading 'CAMERA'
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
Warning in library(pkg_name, lib.loc = lib, character.only = TRUE, logical.return = TRUE) :
  there is no package called 'IPO'
Error: loading failed
Execution halted
*** arch - x64
Warning in library(pkg_name, lib.loc = lib, character.only = TRUE, logical.return = TRUE) :
  there is no package called 'IPO'
Error: loading failed
Execution halted
ERROR: loading failed for 'i386', 'x64'
* removing '[...]/R/win-library/3.2/IPO'
Error: Command failed (1)

Please advise. Thanks in advance.

**Comment by glibiseller** [comment]
Hi,

did you follow the installation description provided in the vignette? (https://github.com/glibiseller/IPO/blob/master/vignette/IPO.Rmd)

Best regards,
Gunnar

**Comment by jheaton1** [comment]
Hi,

Yes, I followed the installation description. See below:

> setwd("D:/")
> library(CAMERA)
Loading required package: Biobase
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following object is masked from ‘package:stats’:

    xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, as.vector, cbind, colnames,
    do.call, duplicated, eval, evalq, Filter, Find, get, intersect,
    is.unsorted, lapply, Map, mapply, match, mget, order, paste, pmax,
    pmax.int, pmin, pmin.int, Position, rank, rbind, Reduce, rep.int,
    rownames, sapply, setdiff, sort, table, tapply, union, unique,
    unlist, unsplit

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

Loading required package: xcms
Loading required package: mzR
Loading required package: Rcpp
Loading required package: ProtGenerics

Attaching package: ‘xcms’

The following objects are masked from ‘package:Biobase’:

    phenoData, phenoData<-

Loading required package: igraph

Attaching package: ‘igraph’

The following object is masked from ‘package:xcms’:

    groups

The following objects are masked from ‘package:BiocGenerics’:

    normalize, union

The following objects are masked from ‘package:stats’:

    decompose, spectrum

The following object is masked from ‘package:base’:

    union

Warning message:
replacing previous import by ‘igraph::groups’ when loading ‘CAMERA’
> library(devtools)
> library(xcms)
> library(rsm)

Attaching package: ‘rsm’

The following object is masked from ‘package:igraph’:

    star

> install_github("glibiseller/IPO")
Downloading github repo glibiseller/IPO@master
Installing IPO
Skipping 2 packages not available: CAMERA, xcms
"C:/PROGRA~1/R/R-32~1.1/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore CMD INSTALL  \
  "C:/Users/~USER /AppData/Local/Temp/RtmpKQFHVp/devtools9543ee14c62/glibiseller-IPO-3738d2a"  \
  --library="\\.../~USER/R/win-library/3.2" --install-tests

* installing *source* package 'IPO' ...
** R
** inst
** tests
** preparing package for lazy loading
Warning: replacing previous import by 'igraph::groups' when loading 'CAMERA'
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
Warning in library(pkg_name, lib.loc = lib, character.only = TRUE, logical.return = TRUE) :
  there is no package called 'IPO'
Error: loading failed
Execution halted
*** arch - x64
Warning in library(pkg_name, lib.loc = lib, character.only = TRUE, logical.return = TRUE) :
  there is no package called 'IPO'
Error: loading failed
Execution halted
ERROR: loading failed for 'i386', 'x64'
* removing '\\.../~USER /R/win-library/3.2/IPO'
Error: Command failed (1)
>

**Comment by glibiseller** [comment]
Hi,

Maybe someone else has an idea why it does not work :-(. 

For the time beeing I could send you the R-package as zip-file and you could install it from source. Please send me a mail to gunnar.libiseller@joanneum.at.

Best regards

**Comment by raimofranke** [comment]
Hi there,

there is an issue with CAMERA and igraph, which has been addressed by a workaround by Martin Morgan on support.bioconductor.org:
https://support.bioconductor.org/p/69414/ 

I am not sure if this is the only problem, but the warning message
"replacing previous import by ‘igraph::groups’ when loading ‘CAMERA’"
shows that this is at least one problem.

Best, Raimo

**Comment by glibiseller** [comment]
Thanks Raimo! That sounds plausible.

**Comment by sneumann** [comment]
It could be that CAMERA-1.25.1 has solved the issue,
in that case you could close this issue.

**Comment by jheaton1** [comment]
Thanks for your help. I will see how it goes.
