### ISSUE TITLE
Better place for IPO WIKI and manual

### ISSUE THREAD

**Issue by tobigithub** [glibiseller/IPO#13]
Hi,
very nice concept, however the manual/wiki pages should have a better place,
It was hard to find how to use that tool. The R man pages are usually not easy readable
but this excellent page is somehow hidden in a path where nobody looks.

https://github.com/glibiseller/IPO/blob/master/vignette/IPO.Rmd

If that would have a central link or would be on https://github.com/glibiseller/IPO/
that would be great.

Best
Tobias

**Comment by glibiseller** [comment]
Hi,

Thanks, that's a good idea. I changed the title and also added a README file which is presented at the bottom of  https://github.com/glibiseller/IPO, It should now guide users to the vignette.

best regards
Gunnar
