### ISSUE TITLE
IPO clean install under Windows "stringi.rdb" missing

### ISSUE THREAD

**Issue by tobigithub** [glibiseller/IPO#14]
Hi,
doing a clean R install (consider a VM) with R.3.2.0 under windows
according to https://github.com/glibiseller/IPO/blob/master/vignette/IPO.Rmd
will lead to 

> library("devtools")
> install_github("glibiseller/IPO") 
Downloading github repo glibiseller/IPO@master
Error in str_detect(url, pattern) : 
  cannot open file '<snip>/R-3.2.0/library/stringi/R/stringi.rdb': No such file or directory
In addition: Warning message:
In str_detect(url, pattern) : restarting interrupted promise evaluation

For those working with R obvious solution, use  install.packages("stringi") or
install.packages("foo", dependencies=TRUE)

I think there are issues with R under WINDOWS, especially working with different versions,
sometimes older versions that are required and R32 and R64 bit dependencies. I think its
quite challenging.
T.

**Comment by glibiseller** [comment]
Hi,

I also think that handling different versions of R, packages on different platform is very challenging. We are planning to get IPO on Bioconductor or CRAN. Availability there could help a lot regarding these issues.  

Thanks for already providing the solution to your problem :smile:.

Best regards
Gunnar
