### ISSUE TITLE
IPO under Windows XP requires R3.03

### ISSUE THREAD

**Issue by tobigithub** [glibiseller/IPO#16]
Hi,
Due to issues with "devtools" the IPO package under WIN XP requires
R 3.03 (which is not the latest version) and Rtools31.exe (which is not the latest version)

Otherwise the following error occours:
"The procedure entry point _chsize_s could not be located in the dynamic link library msvcrt.dll"

The error can *not* be easily solved by copying different msvcrt.dll versions to system32
https://support.microsoft.com/en-us/kb/324762

Additionally this will happen under R 3.2.1 (the newer versions)
Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  unable to load shared object 'C:/Mathematics/R/R-3.2.1/library/git2r/libs/i386/git2r.dll':
  LoadLibrary failure:  The specified procedure could not be found.

Error: package or namespace load failed for ‘devtools’

Cheers
Tobias

**Comment by glibiseller** [comment]
Hi, 
As you already mention it seems like Windows XP only works with Rtools31.exe.
According to  https://github.com/glibiseller/IPO/issues/12 we'll keep track of working system setups in the [wiki](https://github.com/glibiseller/IPO/wiki/known-working-system-configurations).

Cheers
Gunnar
