### ISSUE TITLE
Number of slaves hard coded?

### ISSUE THREAD

**Issue by tobigithub** [glibiseller/IPO#19]
Hi,
The function  optimizeXcmsSet can bemodified to set the number of slaves to spawn.
For example 32, it will do that.

---
resultPeakpicking <- optimizeXcmsSet(files=mzdatafiles[1:4], 
                         params=peakpickingParameters, nSlaves=32, subdir='rsmDirectory')
---

However this and other functions have the following call with "Slaves=4" hard coded
optimizeRetGroup <-
function(xset, params=getDefaultRetGroupStartingParams(), nSlaves=4, subdir="IPO")

Is that correct? Or is that optimized to 4 threads.

Plus once it says "Starting new DOE with" it will print out "nSlaves=1"
BTW this line should be plotted with CR/LF instead of one line, 
I have to set my Monitors to 3840 pixels in order to read that line.

Cheers
Tobias

**Comment by glibiseller** [comment]
Hi,

IPO has it's own parallelization implemented which calculates the different experiments of the DoE in parallel. You can set this parallelization directly with the paramter nSlaves in the function "optimizeXcmsSet" and "optimizeRetGroup". Here, 4 is only a default value. You can set it as you want it and it will be passed through to the following functions.

 Additionally you can set the parallelization for the xcmsSet-function within the parameters you get from getDefaultXcmsSetStartingParams(). When it says "Starting new DoE with" it shows you the parameters used in the xcmsSet-function. Per default the xcmsSet-function itself is used with nSlaves=1 ().
params <- getDefaultXcmsSetStartingParams()
params$nSlaves <- 4

As far as i know grouping and retention time correction can not be calculated in parallel by XCMS at the moment. For these you can only use IPO's parallelization.

Best regards,
Gunnar
