### ISSUE TITLE
IPO in R32 bit vs R64 bit 

### ISSUE THREAD

**Issue by tobigithub** [glibiseller/IPO#20]
Hi,
using the examples from the readme  and retention correlation
https://github.com/glibiseller/IPO/blob/master/vignette/IPO.Rmd

fails in R (32 bit) with 
"Error: cannot allocate vector of size 654.3 Mb"

That is of course not satisfying after waiting 2.2 h 	to finish.
Simple solution is to run IPO always in R (64 bit).

> gc()
          used (Mb) gc trigger   (Mb)  max used   (Mb)
Ncells 1135705 30.4    4755841  127.0   5543382  148.1
Vcells 5040773 38.5  231231507 1764.2 305222496 2328.7

see
https://stat.ethz.ch/R-manual/R-devel/library/base/html/Memory-limits.html  

Cheers
Tobias

**Comment by glibiseller** [comment]
Hi,

thanks for pointing that out. I think the error comes from the function "getTestData" in https://github.com/glibiseller/IPO/blob/master/R/utils.R. This testdata is used to predict the best possible parameters of a response surface model. For every parameter one dimension is needed therefore this object can get quiet big. 

Creating multiple smaller junks of testdata one after another could be solution to the memory problem.

I'll try that for the next update.

Cheers
Gunnar

**Comment by glibiseller** [comment]
Hi,

I replaced the function getTestData with expand.grid.subset in utils.R. This function does not return all test-cases needed but only a subset with maximal 1,000,000 test-cases. I hope this prevents 32-bit systems to run out of memory.

Cheers,
Gunnar
