### ISSUE TITLE
Unable install any packages in R-3.2.2 version

### ISSUE THREAD

**Issue by anupb08** [glibiseller/IPO#30]
After updating to R-3.2.2, I am unable to install any package. It saying the error:

> install.packages("ggplot2")
Installing package into ‘/home/drishti/R/x86_64-redhat-linux-gnu-library/3.2’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
Error in download.file(url, destfile = f, quiet = TRUE) : 
  unsupported URL scheme
Warning: unable to access index for repository https://mirrors.nics.utk.edu/cran/src/contrib
Warning message:
package ‘ggplot2’ is not available (for R version 3.2.2) 

In fact, i tried to install other package, problem is same.
the repository link is accessible from my browser, but i dont know why this error is giving.
Please help.

**Comment by glibiseller** [comment]
Hi!

Sry for the late reply! 
Did you find a solution to your problem? Have you tried the latest R-version?

best regards
Gunnar

**Comment by anupb08** [comment]
Hi Gunnar,
Thanks for reply.
Yes I am able to install packages in latest R version.

Regards,
Anup

On Mon, Oct 12, 2015 at 2:18 PM, Gunnar Libiseller <notifications@github.com

**Comment by glibiseller** [comment]
Thanks for the reply.

**Comment by shlomita** [comment]
Hi,

I have same problem, I cannot install any package in R-3.2.2.
How did you solved the problem?

Thanks.

**Comment by anupb08** [comment]
Hi,
I dont know what exact problem you are facing during package installation.
I can tell you how I installed packages.
After typing install.packages("ggplot") in R console, one popup will be
shown.
In the poup, there will be shown some mirrors. I selected bottom most "HTTP
mirrors".
After selecting this mirror, there  will be shown lots of mirrors. Then you
can select any of them, if that fail you have to try other one.

-Anup

**Comment by glibiseller** [comment]
If you are using R-Studio you can change the mirror in Tools->Global Options...->Packages

**Comment by shlomita** [comment]
I successfully install it with the command:
install.packages("randomForest", repos="http://cran.cnr.berkeley.edu")

Just:
install.packages("randomForest")
Did not worked and give error like  above in the first message.

Thanks a lot!

**Comment by mitrarath** [comment]
I faced the same issue with R-3.2.2. But after googling a bit found that it requires  libcurl suppport in order to be able toh deal with https websites. If you select the mirror which is http....then it would have no issues.

**Comment by johanjordaan** [comment]
Hi. I had the same issue. Doing this:
sudo apt-get install libcurl4-gnutls-dev
Fixed it for me on ubuntu 15.1.

Just for reference and to help other ppl :)

**Comment by rietho** [comment]
Thank you very much for the information!

**Comment by shunshun0914** [comment]
the answer from @shlomita is CORRECT and useful. Thanks a lot .

But I still dont know why it does work. Might be some errors in other repos for this version?

**Comment by vicruiser** [comment]
Hey there,
I've tried everything you've posted here but didn't work. I'm using R 3.2.3 and ubuntu 14.04. Finally I found the solution so that's why I'm posting here an alternative. 
http://packages.ubuntu.com/trusty/gnu-r/r-cran-ggplot2
I've installed every package of that website manually but not in R terminal, in ubuntu terminal. Then I runned R and "library(ggplot2)" worked perfectly. 

Hope this help someone. 
Best wishes!

**Comment by bandhakavi** [comment]
i just changed the mirror from a https one to a http.

**Comment by harshilsaini** [comment]
please help guys non of the method is working for me i am using ubuntu 16.04LTS

**Comment by rietho** [comment]
@harshilsaini It's diffiucult to help you without more information (how do you run R, why did the other proposed solutions not work).
As your issue is not IPO-related I'd suggest to post your question with more details at [Stackoverflow](http://stackoverflow.com/) or if it's rather Ubuntu related on [Ask Ubuntu](http://askubuntu.com/)

**Comment by venkat01** [comment]
When selecting the mirrors for install.packages("ggplot2"), choose the http and not the https as that is the issue that i had.

**Comment by Jeet1994** [comment]
Hello all,

type the following in RStudio :` options(download.file.method="libcurl")`

And then try installing. 

Solved the same problem for me. 

Regards.

**Comment by sriprad** [comment]
Hi, I am unable to install tidytext in 3.2.2 . any clue?

**Comment by Sangeetha-Dns** [comment]
> Hello all,
> 
> type the following in RStudio :`options(download.file.method="libcurl")`
> 
> And then try installing.
> 
> Solved the same problem for me.
> 
> Regards.

Thank you very much this really fixed my package installation issue!! perhaps after going through all other listed solutions on web-pages which did not help fix the repository access issue!

**Comment by lecorguille** [comment]
An alternative could be to install IPO using Conda/Miniconda
https://anaconda.org/bioconda/r-ipo
