### ISSUE TITLE
Unexpected problems with the netCDF and mzXML files

### ISSUE THREAD

**Issue by Jiaqc** [glibiseller/IPO#32]
Dear Gunnar,

I'm sorry to bother you again.
Recently, I have met some unexpected problems handling metanolomics data by IPO. Here are the details.

(1) Instrument: UFLC-IT-TOF-MS (SHIMADZU)
File type from vendor software (LCMSSolution, SHIMADZU): .lcd

(2) If I converted the .lcd files to .netCDF files by vendor software, (since the mass spectrometry switch between positive and negative models) the data were sorted by the scan time with one positive record followed by one negative record. IPO failed to pick peaks with the method “centWave”.

Then I tried to converte the .lcd files to .mzXML (or .mzData) files, and each .lcd file would generate two .mzXML files containing positive and negative records respectively. When handing the positive or negative data, IPO failed to detect isotope ions neither. 
I checked the .mzXML files by OpenChrom and found something strange. It seems that the mass data were un-centroided or false centroided. Part of the data at the same scan time sorted by mz values were below.
m/z	abundance
230.21	0
230.225	8832
230.239	15360
230.254	13184
230.268	0
256.232	0
256.247	15360
256.262	19712
256.277	13184
256.293	0

It is very different with the .netCDF file. 
m/z	abundance
230.24	124278
231.24	8832
256.26	37504

The vender software seemed to be wrong when converting the .lcd files to mzXML files (or mzData). 

How could I get the appropriate .netCDF files for IPO? I do really need a method to transform the .netCDF file to two separated .netCDF files with one containing the positive data and another containing the negative data. I have tried the R package “ncdf” to transform the files, but failed since I am not familiar with R.

Since the network of xcms-websites doesn’t work, I am sorry to interrupt you.
Looking forward to your help and advises!
Thanks in advance.

Best Regards,
Jiaq Chen

**Comment by sneumann** [comment]
Dear Jiaq, can I ask you to post this question 
to http://www.metabolomics-forum.com/
and send me the link of the post ?
I know the answer, and then I can post it there.
Yours, Steffen
