### ISSUE TITLE
Installing IPO error

### ISSUE THREAD

**Issue by jjkellogg** [glibiseller/IPO#34]
I'm a bit of an R novice, but when installing IPO with R 3.2.2, I get the following error:

> install_github("glibiseller/IPO")
Downloading GitHub repo glibiseller/IPO@master
Installing IPO
"C:/Program Files/R/R-32~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  "C:/Users/jjkellog/AppData/Local/Temp/Rtmpqkznw3/devtools5b863d91ce0/glibiseller-IPO-47aff39"  \
  --library="C:/Users/jjkellog/Documents/R/win-library/3.2" --install-tests 

'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
Error: Command failed (1)
>

Everything else, the devtools and Rtools, installed just fine, it is getting IPO installed that is serving up this error.

**Comment by rietho** [comment]
This seems to be a windows installing issue.
Please see the following [thread](https://github.com/ramnathv/slidify/issues/247) for a possible solution.
I hope this helps.

**Comment by jjkellogg** [comment]
Thank you!  I don't usually use a Windows machine, so the error tripped me up.  But that thread helped me get the paths right, and it's working just fine.  Thank you again!
