### ISSUE TITLE
optimizeRetGroup ignoring retcorMethod="loess"

### ISSUE THREAD

**Issue by sneumann** [glibiseller/IPO#36]
Hi, it seems that `optimizeRetGroup()` is somehow still 
using `method="obiwarp"` even if the retcorGroupParameters
were created with `getDefaultRetGroupStartingParams(retcorMethod="loess")`

````
retcorGroupParameters <- getDefaultRetGroupStartingParams(retcorMethod="loess")
retcorGroupParameters$profStep <- 1

resultRetcorGroup <- optimizeRetGroup(xset=optimizedXcmsSetObject, params=retcorGroupParameters, 
                                      nSlaves=1, subdir="rsmDirectory")
````

results in:

````
> resultRetcorGroup$best_settings$retcorMethod
[1] "obiwarp"
````

Yours, Steffen

**Comment by rietho** [comment]
That's really interesting. On a first quick glance, I could not find the problem. I'll have a look tomorrow and fix it asap.

**Comment by sneumann** [comment]
Indeed, my fault. When trying to create a minimal 
standalone example, I could not reproduce the issue. 
Case closed :-)

````
library(IPO)
library(faahKO)
library(RUnit)

xsg <- group(faahko)

retcorGroupParameters <- getDefaultRetGroupStartingParams(retcorMethod="loess")

retcorGroupParameters$profStep <- 1
retcorGroupParameters$missing <- 0
retcorGroupParameters$extra <- 0
retcorGroupParameters$minfrac <- 0.75
retcorGroupParameters$max <- 50

resultRetcorGroup <- optimizeRetGroup(xset=xsg, params=retcorGroupParameters, nSlaves=1, subdir="rsmDirectory")

checkEquals(resultRetcorGroup$best_settings$retcorMethod, "loess")
````

**Comment by sneumann** [comment]
Actually, almost :-)
When optimising with `retcorMethod="loess"`, 
IPO still tries to go through different "center" samples:

````
missing: c(0, 2)
extra: c(0, 2)
span: c(0.001, 0.22)
bw: c(0.879999999999999, 23.92)
minfrac: c(0.54, 1)
mzwid: c(1e-04, 0.0241)
smooth: loess
family: gaussian
plottype: none
retcorMethod: loess
minsamp: 1
max: 50
profStep: 1
center: 18
````
and also tried different `center`, which makes no sense with `retcorMethod="loess"`
Since center is not part of the list returned by `getDefaultRetGroupStartingParams(retcorMethod="loess"), 
it seems to be treated separately.

**Comment by rietho** [comment]
So the issue still persisting?

**Comment by sneumann** [comment]
In a subsequent step `writeRScript(paramsPP, resultRetcorGroup$best_settings, 1)` 
I had left out the `$best_settings` , and that mislead me to thinking that something 
was wrong with "loess". Sorry for the confusion.

**Comment by rietho** [comment]
No worries. It's good to hear, that `optimizeRetGroup ` correctly recognizes the method for retention time correction.
