### ISSUE TITLE
IPO error message for UseMethod("sendData")

### ISSUE THREAD

**Issue by leichtle** [glibiseller/IPO#37]
Dear developers team,
Running the IPO scripts ('optimize XcmsSet()') I run into the error:

> Fehler in UseMethod("sendData") : 
nicht anwendbare Methode für 'sendData' auf Objekt der Klasse "c('forknode', 'SOCK0node')" angewendet
 (in German, meaning "Error in UseMethod("sendData") : not applicable method for 'sendData' on an object of class "c('forknode', 'SOCK0node')"").

_Description:_

- System: R 3.2.4 on Debian 8.4, all packages actualized.
- Packages load properly.
- A new DoE is started when the function 'optimize XcmsSet()' is called.
- Package 'snow' is attached.
- A snow cluster is started with [nSlaves] local sockets.
- Image 'rsm_1.jpg' is drawn.
- A new DoE is started automatedly with a different parametrization.
- After the expected runtime, the run stops with the above-mentioned error message.

_Suspicion:_
IPO calls 'parallel', and after the execution of the DoE code, 'snow' is attached. I suppose, 'snow' should be detached before a new DoE run starts. A similar [issue](http://finzi.psych.upenn.edu/library/secr/html/Parallel.html) has been described for package {secr}.
Any help would be greatly appreciated!
Best regards,
Alex

**Comment by rietho** [comment]
Thank you sharing your issue!
We already discovered this problem and so we can confirm your proposed solution. I'll push a fix today and will let you know.

**Comment by rietho** [comment]
Ok, IPO is now on version 1.7.5 and your issue should be fixed. Can you confirm that?

**Comment by leichtle** [comment]
Seems to run properly now. Many thanks & best regards,
Alex
