### ISSUE TITLE
Meaningful colnames for calcPPS() result

### ISSUE THREAD

**Issue by sneumann** [glibiseller/IPO#4]
Currently, calcPPS() returns:

````
> calcPPS(iporesult$best_settings$xset)
     [,1] [,2] [,3] [,4]    [,5]
[1,]    0  692  462  194 81.4632
````
There should be reasonable column names mentioning 

     1. Space for experimentid of the Design of Experiments (0 since not known in calcPPS)
     2. Number of peaks
     3. Number of peaks without LIP and RP
     4. Reliable peaks (RP)
     5. Peak picking score (PPS)

Another question is why that is a one-row array, are there cases imaginable 
where calcPPS() returns multiple values ? If not, I suggest simplifying 
to a vector.

**Comment by glibiseller** [comment]
Thanks for your suggestions.
In the next update I'll change the type of the return value of calcPPS() to a vector and add names.
