### ISSUE TITLE
Allow to select the retcor() method

### ISSUE THREAD

**Issue by sneumann** [glibiseller/IPO#8]
Hi, the retcor(method="loess") has quite a performance benefit 
over the method="obiwarp", so it would be cool if that could 
be optimised as well. The downside is that this requires 
method-dependent getDefaultRetGroupStartingParams().

Also, obiwarp is independent of the grouping, while loess depends 
on reasonable grouping. If oscillation of optimal parameters occurs, 
that could be a reason. Yours, Steffen

**Comment by glibiseller** [comment]
Hi Steffen!

It sure would be benefical if IPO supports all XCMS-methods. I think this enhancement and the enhancement [issue 5](https://github.com/glibiseller/IPO/issues/5) can be done together.
I hope i can start to work on it next week.

best regards

**Comment by glibiseller** [comment]
Hi Steffen!

Do you have a suggestion for the minimum value for the parameter "span" of the method retcor.loess. Is zero fine or should it be 0.001.

Yours, Gunnar

**Comment by glibiseller** [comment]
Implemented in version 1.7.0
